version: "3"

services:

  db:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    networks:
      - backend

  springbackend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
    networks:
      - backend
    environment:
      DB_HOST: db

networks:
  backend:

